// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9vwqMp75Bz2jiJ9baCmNZsX1-h7rbR94',
    appId: '1:458155795750:web:528ea03afb0e9c18ca8de7',
    messagingSenderId: '458155795750',
    projectId: 'toms-palace',
    authDomain: 'toms-palace.firebaseapp.com',
    storageBucket: 'toms-palace.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhLBYGKExdw6UPpS9l-v5Gv91OCq0shFo',
    appId: '1:458155795750:android:de116bf6eef49697ca8de7',
    messagingSenderId: '458155795750',
    projectId: 'toms-palace',
    storageBucket: 'toms-palace.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2NbDAajrbpC63rs0etyyBvflaHE-MaII',
    appId: '1:458155795750:ios:669ad888d603c6d3ca8de7',
    messagingSenderId: '458155795750',
    projectId: 'toms-palace',
    storageBucket: 'toms-palace.appspot.com',
    iosClientId: '458155795750-taa1lf0seblvik3mh1p0atqobsl3q702.apps.googleusercontent.com',
    iosBundleId: 'com.example.tomsPalace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2NbDAajrbpC63rs0etyyBvflaHE-MaII',
    appId: '1:458155795750:ios:669ad888d603c6d3ca8de7',
    messagingSenderId: '458155795750',
    projectId: 'toms-palace',
    storageBucket: 'toms-palace.appspot.com',
    iosClientId: '458155795750-taa1lf0seblvik3mh1p0atqobsl3q702.apps.googleusercontent.com',
    iosBundleId: 'com.example.tomsPalace',
  );
}
